"""initial schema

Revision ID: 461dcf5af494
Revises:
Create Date: 2026-09-13 20:07:01.154568+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "461dcf5af494"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runs",
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("dataset_name", sa.String(length=200), nullable=False),
        sa.Column("dataset_version", sa.String(length=50), nullable=False),
        sa.Column("rubric_id", sa.String(length=200), nullable=False),
        sa.Column("rubric_version", sa.String(length=50), nullable=False),
        sa.Column("rubric_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("passed", sa.Integer(), nullable=False),
        sa.Column("failed", sa.Integer(), nullable=False),
        sa.Column("errored", sa.Integer(), nullable=False),
        sa.Column("pass_rate", sa.Float(), nullable=False),
        sa.Column("mean_score", sa.Float(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_index(op.f("ix_runs_dataset_name"), "runs", ["dataset_name"], unique=False)
    op.create_index(
        "ix_runs_rubric_created", "runs", ["rubric_fingerprint", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_runs_rubric_fingerprint"), "runs", ["rubric_fingerprint"], unique=False
    )
    op.create_index(op.f("ix_runs_rubric_id"), "runs", ["rubric_id"], unique=False)
    op.create_index(op.f("ix_runs_status"), "runs", ["status"], unique=False)
    op.create_table(
        "judgements",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("case_id", sa.String(length=200), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("verdict", sa.String(length=20), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=False),
        sa.Column("criterion_scores", sa.JSON(), nullable=False),
        sa.Column("flags", sa.JSON(), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("family", sa.String(length=50), nullable=False),
        sa.Column("elapsed_ms", sa.Float(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["runs.run_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_judgements_case_id"), "judgements", ["case_id"], unique=False)
    op.create_index("ix_judgements_run_case", "judgements", ["run_id", "case_id"], unique=True)
    op.create_index(op.f("ix_judgements_run_id"), "judgements", ["run_id"], unique=False)
    op.create_index(op.f("ix_judgements_verdict"), "judgements", ["verdict"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_judgements_verdict"), table_name="judgements")
    op.drop_index(op.f("ix_judgements_run_id"), table_name="judgements")
    op.drop_index("ix_judgements_run_case", table_name="judgements")
    op.drop_index(op.f("ix_judgements_case_id"), table_name="judgements")
    op.drop_table("judgements")
    op.drop_index(op.f("ix_runs_status"), table_name="runs")
    op.drop_index(op.f("ix_runs_rubric_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_rubric_fingerprint"), table_name="runs")
    op.drop_index("ix_runs_rubric_created", table_name="runs")
    op.drop_index(op.f("ix_runs_dataset_name"), table_name="runs")
    op.drop_table("runs")
    # ### end Alembic commands ###
